### ISSUE TITLE
dmaker.fan.p18 issue

### ISSUE THREAD

**Issue by sagitt** [ikaruswill/lovelace-fan-xiaomi#89]
Using my new: Mi Smart Standing Fan 2 | dmaker.fan.p18 | BPLDS02DM | AC, 15W, 30.2-55.8bBi... with xiaomi_miio_fan custom integration from hacs, i found these problems:

- I can't operate with angle 140° (120 switch directly to 30). This fan support it by native app. (see picture)
- 4 speeds have different position respects the 4 speeds in app, for example Speed 1 in card is just before speed 2 in app. (see picture)
- Pressing "Natural" it correctly switch from direct to natural mode in the app, but i can't see te right status on the card (if natural is active or not and change it to direct mode again)
- This device have the hide led option, I enabled it in the card but i can't see any button or status for it.
- This device have the "sound on\off" switch, there is a way for have it in the card?

![IMG_0BE880AEE22D-1](https://user-images.githubusercontent.com/169086/169711664-0e225265-5b5a-4d75-a68d-b79a7d4f5820.jpeg)
![IMG_0569](https://user-images.githubusercontent.com/169086/169711763-d4f51b5b-c135-4c88-8d8a-cf5758a651de.PNG)
![Schermata 2022-05-22 alle 21 07 46](https://user-images.githubusercontent.com/169086/169711768-c31a9abd-4eff-4590-9c81-87690b9f5204.png)

thanks.

**Comment by mattsches** [comment]
Maybe I should better open a separate ticket, but since I have similar problems with the same model using the same integration (xiaomi_miio_fan), I add it here.

I cannot switch to natural mode, but I'm getting an error:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/xiaomi_miio_fan/fan.py:950
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:17:51 (2 occurrences)
Last logged: 10:18:01

[140626650422720] 'Nature'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/config/custom_components/xiaomi_miio_fan/fan.py", line 950, in async_set_preset_mode
    FAN_PRESET_MODE_VALUES_P5[preset_mode],
KeyError: 'Nature'
```

I suspect that the wrong method is called here?

**Comment by ikaruswill** [comment]
@mattsches The nature mode should be fixed in 2.2.0. Problem was case sensitivity of the preset mode.
@sagitt 140 angle support has been added for your fan in 2.2.0, speed logic has also been changed, could you check and let me know if you're still facing this issue?

**Comment by mattsches** [comment]
I am sorry to say that the error still occurs with the new version 2.2.0.

I wonder if the strings in [this line](https://github.com/ikaruswill/lovelace-fan-xiaomi/blob/3f2428aafcaa07ef13f61502cd1a2991d1421bae/src/xiaomi-fan-card.ts#L734) should be all lowercase, too?

**Comment by sagitt** [comment]
my system won't load the card after update

**Comment by ikaruswill** [comment]
Won't load as in what error are you seeing? 

The upgrade has some changes in the code structure due to deprecations in Home Assistant.

**Comment by sagitt** [comment]
> Won't load as in what error are you seeing?
> 
> The upgrade has some changes in the code structure due to deprecations in Home Assistant.

i see nothing, but i see it if set to "default", but i can control only on\off.. have error on services for other thing (it's ok, i'm not using default integration)

**Comment by ikaruswill** [comment]
Do you have a screenshot perhaps? And does the edit mode on the dashboard show any error?

**Comment by sagitt** [comment]
> Do you have a screenshot perhaps? And does the edit mode on the dashboard show any error?
> 
> 

![image](https://user-images.githubusercontent.com/169086/180496471-aa76664a-62ed-4fe3-b34c-b2323f890328.png)
![image](https://user-images.githubusercontent.com/169086/180496493-56aaab2d-b903-46da-8e49-02bda996ac19.png)
![image](https://user-images.githubusercontent.com/169086/180496514-b72b4520-c36d-43b3-bc0b-de53172c4599.png)

**Comment by ikaruswill** [comment]
Hmm I see. Okay let me figure this out tomorrow. Meanwhile maybe you can install 2.1.0 to keep it working.

**Comment by sagitt** [comment]
> Hmm I see. Okay let me figure this out tomorrow. Meanwhile maybe you can install 2.1.0 to keep it working.

I'll wait :)

**Comment by ikaruswill** [comment]
Hi @sagitt there are some outstanding issues on mobile with 2.2.0 unfortunately, this might take some time to resolve.

Meanwhile, I'd like to know a few things:
1. Does this work on desktop for you?
2. 'default' Platform works to toggle on and off right? Which integration are you using to connect the dmaker.fan.p18? Is it [syssi/xiaomi_fan](https://github.com/syssi/xiaomi_fan)?
3. Can you provide some examples of the service call errors that you mentioned?

**Comment by sagitt** [comment]
> Hi @sagitt there are some outstanding issues on mobile with 2.2.0 unfortunately, this might take some time to resolve.
> 
> 
> 
> Meanwhile, I'd like to know a few things:
> 
> 1. I noticed from the screenshots that you're on mobile. Does this work on desktop for you?
> 
> 2. 'default' Platform works to toggle on and off right? Which integration are you using to connect the dmaker.fan.p18? Is it [syssi/xiaomi_fan](https://github.com/syssi/xiaomi_fan)?
> 
> 3. Can you provide some examples of the service call errors that you mentioned?

Same on dekstop
I'm using xiomi mi smart pedestal fan integration
Mi hacs now won't load something about this card
I'll send you error of service call 
![image](https://user-images.githubusercontent.com/169086/180603203-97fc428d-c4b2-436c-8c86-a0a5966b76f2.png)

**Comment by sagitt** [comment]
> Hmm I see. Okay let me figure this out tomorrow. Meanwhile maybe you can install 2.1.0 to keep it working.

Now afeter upgrade to 2.2.1 i cam see it but unusable on mobile. ![image](https://user-images.githubusercontent.com/169086/180657664-7cdfbf43-0e8e-41db-8f3b-7acaf37d5b33.png)

**Comment by sagitt** [comment]
> Hi @sagitt there are some outstanding issues on mobile with 2.2.0 unfortunately, this might take some time to resolve.
> 
> 
> 
> Meanwhile, I'd like to know a few things:
> 
> 1. I noticed from the screenshots that you're on mobile. Does this work on desktop for you?
> 
> 2. 'default' Platform works to toggle on and off right? Which integration are you using to connect the dmaker.fan.p18? Is it [syssi/xiaomi_fan](https://github.com/syssi/xiaomi_fan)?
> 
> 3. Can you provide some examples of the service call errors that you mentioned?

Will you release a new version for fix these problems?

For now i done a downgrade.

**Comment by Subdarub** [comment]
The nature mode problem still exists btw.
It still calls for a Preset while it instead should call for "Mode".

On both 2.0 and 2.1

If you need any troublshooting assistance please let me know. @ikaruswill

**Comment by linsvensson** [comment]
I'm having a similar problem with the pro version of this fan (dmaker.fan.p33).
Would love to see this fixed.

**Comment by ikaruswill** [comment]
Hi everyone, I understand this has been an issue for many, but unfortunately I have my hands full with a life event of mine and won't be able to dedicate time to this until late September. 

Meanwhile, I'd be happy to approve PRs or give anyone who's willing to give this a go, developer access. Appreciate your patience on this. 🙏
